### ISSUE TITLE
File type images are not directly accepted

### ISSUE THREAD

**Issue by Medtalbbrahim** [codenameakshay/async_wallpaper#14]
Welcome
I have a problem with this package
For example, if you choose an image from the phone and want to set it as wallpaper, this is not possible
Because it does not accept images of file type directly without flutter_cache_manager
Please help me solve this problem

**Comment by codenameakshay** [comment]
PR #62 addresses this directly: local images can now be supplied with `WallpaperSource.filePath(path)`, so an app no longer needs `flutter_cache_manager` merely to convert a picked file into an accepted wallpaper source.

Please test the 3.2.0 branch:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please try a readable file returned by your picker and share the source path/type, Android version, and returned result status if it does not apply.
