### ISSUE TITLE
After successfully setting the wallpaper, return to the previous screen.

### ISSUE THREAD

**Issue by dinhtrung3008** [codenameakshay/async_wallpaper#22]
I think it is not necessary to go back to the previous screen, just display the successful setup message.

**Comment by BensonGathu** [comment]
Having the same issue, How did you fix it?

**Comment by adverthouse** [comment]
same here

**Comment by codenameakshay** [comment]
PR #62 removes package-owned delayed navigation and package-owned success UI. The plugin no longer sends the app home or forces a return after applying a wallpaper; the caller owns navigation and messaging. The legacy `goToHome` argument remains only for source compatibility and is intentionally ignored.

Please test the 3.2.0 branch:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please confirm that a direct apply leaves your app on its current screen and share the returned result if you still see unexpected navigation.
