### ISSUE TITLE
After setting live wallpaper the service app is not removing from foreground Please remove app from foreground when live wallpaper is set.

### ISSUE THREAD

**Issue by tayab72323** [codenameakshay/async_wallpaper#24]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter:**
 - version
 - channel

**Dart:**
 - version

**Additional context**

**Comment by codenameakshay** [comment]
PR #62 replaces the old video setup path with an Android `WallpaperService` whose `MediaPlayer` follows wallpaper visibility and surface lifecycle. Playback pauses/resumes with visibility and uses one release path when the engine is destroyed. It does not start or retain an app foreground service or notification.

Please test the 3.2.0 branch:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

After selecting a video wallpaper, please report whether a foreground notification or app service remains. If possible, include the relevant output from `adb shell dumpsys activity services`.
