### ISSUE TITLE
When i set wallpaper from file using async wallpaper package the image got stretches .but when i set the same image from device it set perfect.  

### ISSUE THREAD

**Issue by A4Aaditya** [codenameakshay/async_wallpaper#26]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter:**
 - version
 - channel

**Dart:**
 - version

**Additional context**

**Comment by codenameakshay** [comment]
PR #62 adds explicit scale handling for file wallpapers, so a local image is no longer implicitly stretched. The available modes are `centerCrop`, `fitCenter`, `center`, `fill`, and `stretch`; for this report, please try `centerCrop` and `fitCenter`.

Please test the 3.2.0 branch with the same image:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please report the source image dimensions, device resolution, selected scale mode, and whether either mode produces the expected result.
