### ISSUE TITLE
setLiveWallpaper feature decrease supported device

### ISSUE THREAD

**Issue by cool2apps** [codenameakshay/async_wallpaper#28]
**Is your feature request related to a problem? Please describe.**
setLiveWallpaper feature decreases supported device dramatically on play store.

**Describe the solution you'd like**
There should be a method to disable Live Wallpaper feature.

**Describe alternatives you've considered**
I guess this package adds the line below to AndroidManifest.xml
```
    <uses-feature android:name="android.software.live_wallpaper" android:required="true"/>
```
If we can change it like below, this will solve the problem.
```
    <uses-feature android:name="android.software.live_wallpaper" android:required="false"/>
```

**Additional context**

**Comment by codenameakshay** [comment]
PR #62 fixes the manifest filtering problem by declaring `android.software.live_wallpaper` with `android:required="false"`. Static-wallpaper users should no longer be excluded from installation or Play device compatibility merely because a device lacks live-wallpaper support.

Please test the 3.2.0 branch:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please inspect the merged manifest and, if available, the Play Console device catalog. Report any device that is still filtered solely because of the live-wallpaper feature.
