### ISSUE TITLE
the toast message for successfully pop up before setting the wallpaper

### ISSUE THREAD

**Issue by GodfreyMelchior** [codenameakshay/async_wallpaper#30]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter:**
 - version
 - channel

**Dart:**
 - version

**Additional context**

**Comment by thanhnguyen1121** [comment]
i face the same issue... did you find the solution?

**Comment by codenameakshay** [comment]
PR #62 removes the package-owned success toast. The API now returns a structured state so the caller can decide when to show UI: a direct static operation can report `applied`, while live/UI flows can report `previewOpened` or `awaitingUserConfirmation`. This avoids announcing success before Android's system preview has completed.

Please test the 3.2.0 branch:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please confirm that no plugin toast appears and share the returned status for the flow you tested.
