### ISSUE TITLE
on setting a wallpaper for livewallpaper the bottomsheet that contains set wallpaper button comes with the name of the plugin, find a way to override the name of the plugin by the name of the app

### ISSUE THREAD

**Issue by GodfreyMelchior** [codenameakshay/async_wallpaper#31]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Flutter:**
 - version
 - channel

**Dart:**
 - version

**Additional context**

**Comment by Sanaullah49** [comment]
Goto Your Project > External Libraries > Flutter Plugins > async_wallpaper > android > src.main > res > values > strings.xml
and replace the app_name with your desired title

**Comment by codenameakshay** [comment]
PR #62 fixes the plugin-name branding by using resources that the consuming app can override. Add the following to a values XML file in your app, such as `android/app/src/main/res/values/async_wallpaper.xml`:

```xml
<resources>
    <string name="async_wallpaper_video_live_wallpaper_label">Your app name</string>
    <string name="async_wallpaper_opengl_live_wallpaper_label">Your app name</string>
    <string name="async_wallpaper_live_wallpaper_description">Your description</string>
</resources>
```

Please test the 3.2.0 branch:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please report the exact service label/description displayed in the live-wallpaper bottom sheet after the override.
