### ISSUE TITLE
Live Wallpapers Missing issue

### ISSUE THREAD

**Issue by UbAidu21** [codenameakshay/async_wallpaper#34]
The problem I'm facing is when I apply the live wallpaper on Home Screen it only, on some devices it either removes the LockScreen Wallpaper as well and the default wallpaper for screen is applies. And on some devices it applies on both e.g. Home Screen and Lock Screen., while I want to set the wallpaper of Home screen only and leave the lock screen wallpaper as it is.

**Comment by codenameakshay** [comment]
This is the same Android/OEM system-preview boundary affecting live wallpapers: on some devices the preview applies both screens or replaces the lock wallpaper even when home is requested. The plugin cannot portably force the OEM preview to preserve the lock screen or observe its final choice.

PR #62 avoids reporting a false application result. It returns the requested target together with a preview/confirmation state, while direct static wallpaper operations retain separate target outcomes.

Please test the 3.2.0 branch:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please share the device/OEM build, requested target, returned status, preview choices, and exact home/lock result so we can document that device's behavior.
