### ISSUE TITLE
Exception java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by WaseemAbbasi22** [codenameakshay/async_wallpaper#35]
**Describe the bug**
my app crash  while using this  plugin when user try to set the wallpaper then app crashes with this exeception reply already submitted which is inside the plugin

**To Reproduce**
 await AsyncWallpaper.setWallpaper(
        url: url,
        wallpaperLocation: wallpaperLocation,
        errorToastDetails: ToastDetails.error(),
      )

**Expected behavior**
App didn't crash while setting wallpaper 

**Flutter:**
3.19.0
 - channel
stable
**Dart:**
 - version
Dart 3.3.0

**Comment by trung152** [comment]
i am also facing the same issue

**Comment by oit-prabhat-patel** [comment]
I am also facing this issue

**Comment by codenameakshay** [comment]
PR #62 fixes the `Reply already submitted` race by serializing wallpaper mutations through one FIFO operation queue and protecting every platform-channel completion with exactly-once delivery, including shutdown and rejected-operation paths.

Please test the 3.2.0 branch with rapid/repeated wallpaper calls:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please share the call sequence, device/Android version, result from each call, and a complete new stack trace if any duplicate reply or crash remains.
