### ISSUE TITLE
CenterCrop

### ISSUE THREAD

**Issue by unesbnn** [codenameakshay/async_wallpaper#6]
Hello,

Is there a way to center the wallpaper?

**Comment by Pavel401** [comment]
Any solution?

**Comment by DiTuStudio** [comment]
Any solution ?

**Comment by codenameakshay** [comment]
Thanks for reporting this. PR #62 adds explicit static-image scale modes instead of forcing a single crop path: `centerCrop`, `fitCenter`, `center`, `fill`, and `stretch`. The scaling is applied consistently to URL, file, content-URI, and byte sources.

Please test the 3.2.0 branch with:

```yaml
dependencies:
  async_wallpaper:
    git:
      url: https://github.com/codenameakshay/async_wallpaper.git
      ref: codex/3.2.0-wallpaper-engine
```

Then run:

```bash
flutter pub get
```

Please try `centerCrop` with the same image and tell us the device model, image dimensions, and whether the framing now matches what you expected.
